# site settings
title: Kontinu
subtitle: Devops Bootcamps & Consultoria
email: info@kontinu.io
description: Bootcamps y Consultoria Devops, Docker, kubernetes, Cloud, Transformacion Digital.
baseurl: "/nova-home" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kontinu

street_address: Guatemala City
city: Guatemala
state: Guatemala
zip_code: 01001
country: Guatemala
phone: +(502) 4555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url: https://www.facebook.com/Kontinu-107035944399082
github_url: https://github.com/kontinu
gitlab_url: https://gitlab.com/kontinu
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/marcos-cano-804a1787/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - .img-sources/
  - "*.sh"
  - docker-compose.yml
  - README.md
  - Gemfile*
  - .gitlab-ci.yml
  - LICENSE
  - experiments
  - .gitignore
  - .git
  - LICENSE

# CURRENT BOOTCAMPS
bootcamp:
  name: "Docker Bootcamp v1.0 - Core"
  url: https://www.eventbrite.com/e/docker-bootcamp-v15-core-tickets-112070776710
